<?php
/**
 * @file
 * Primary module hooks for Tour Media module.
 *
 */

/*
 * Argument #2 ($field_storage) must be of type 
 * Drupal\field\Entity\FieldStorageConfigInterface,
 * Drupal\field\Entity\FieldStorageConfig given,
 */

use Drupal\field\Entity\FieldStorageConfig;
/**
 * Implements hook_field_views_data_alter().
 *
 * Views integration for entity reference fields which reference nodes.
 * Adds a term relationship to the default field data.
 *
 * @see views_field_default_views_data()
 */
function tour_media_field_views_data_alter(array &$data, FieldStorageConfig $field_storage) {
  if ($field_storage->getType() == 'entity_reference' && $field_storage->getSetting('target_type') == 'node') {
    foreach ($data as $table_name => $table_data) {
      foreach ($table_data as $field_name => $field_data) {
        if (isset($field_data['filter']) && $field_name != 'delta') {
          $data[$table_name][$field_name]['filter']['id'] = 'node_index_nid';
        }
      }
    }
  }
}
